### PR TITLE
Update lib definition

### PR DESCRIPTION
**Pull request by retyui**
via: https://github.com/ARDcode/react-native-appmetrica-yandex/issues/14

To test [UserProfileConfig](https://www.typescriptlang.org/play?#code/AQ4FwTwBwU2BVAzjATgBRQewGYEsA2MAwpgHZ4DmwAvMAN4BQozwpAhgLYwD8AXMIjApcpCgBomLEBRikAJqj7AA5Nhgc2hZcAA+KjVt0ChIqnoBumXHIlSQbGUtIBXDgCNUtu29wowACwARNjAefmDQowBtF3dUAF1o2I8UMVZXFMS9GIzPdLjU-MyjS2svKVJMMFw8AGMQ3DJEAFF2N0I5JTdMTEI2UnLgAF9gADJ6SSkogGsYCH5BYVF4hZNRI2TUI27emH7BoYYj5nM2FGA2fiRUDBwCYjJKakY7C5leAEZB5kvgL8mWG5eMoAEzKb6gWr8ITOGAQkByfh0Ibw4CI4BReKoij8UgwADuwAiMAAFAAGACUByAA)

### CODE REVIEW

**Comment by ARDcode** [comment]
@retyui thx for PR:)

**Comment by retyui** [comment]
@ARDcode do you have plans to release a new version?

**Comment by ARDcode** [comment]
@retyui will release today

**Comment by retyui** [comment]
@ARDcode  I DON'T BELIEVE YOU

image

**Pull request merged**
